---
title: "summary_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r }
library(tidyverse)
install.packages("sqldf")
library(sqldf)
n_max = 200 # Inf


melbourne = c('http://data.insideairbnb.com/australia/vic/melbourne/2022-03-09/data/listings.csv.gz', 'http://data.insideairbnb.com/australia/vic/melbourne/2022-03-09/data/calendar.csv.gz', 'http://data.insideairbnb.com/australia/vic/melbourne/2022-03-09/data/reviews.csv.gz')
datasets_melbourne <- lapply(melbourne, read_csv, n_max = n_max)

sydney = c('http://data.insideairbnb.com/australia/nsw/sydney/2022-03-09/data/listings.csv.gz', 'http://data.insideairbnb.com/australia/nsw/sydney/2022-03-09/data/calendar.csv.gz', 'http://data.insideairbnb.com/australia/nsw/sydney/2022-03-09/data/reviews.csv.gz')
datasets_sydney <- lapply(sydney, read_csv, n_max = n_max)

barcelona = c('http://data.insideairbnb.com/spain/catalonia/barcelona/2022-03-10/data/listings.csv.gz', 'http://data.insideairbnb.com/spain/catalonia/barcelona/2022-03-10/data/calendar.csv.gz', 'http://data.insideairbnb.com/spain/catalonia/barcelona/2022-03-10/data/reviews.csv.gz')
datasets_barcelona <- lapply(barcelona, read_csv, n_max = n_max)

madrid = c('http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2022-03-10/data/listings.csv.gz', 'http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2022-03-10/data/calendar.csv.gz', 'http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2022-03-10/data/reviews.csv.gz')
datasets_madrid <- lapply(madrid, read_csv, n_max = n_max)
```


```{r }
#head statements for all listings
head(datasets_melbourne[[1]])
head(datasets_sydney[1])
head(datasets_barcelona[1])
head(datasets_madrid[1])
```

# make summary
```{r }
lapply(datasets_madrid, summary)

```


# make function that does summary for all objects
```{r }
for (ds in datasets_madrid) {
  #summary_statistics <- 
  #lapply(datasets_madrid, summary)
  summary_statistics = summary(ds)
  print(summary_statistics)
}
```


```{r }
# combine all calendar dataframes
all_calendar <-  bind_rows(cbind(city='madrid', datasets_madrid[[2]]), 
                 cbind(city='barcelona',datasets_barcelona[[2]]),
                 cbind(city='melbourne',datasets_melbourne[[2]]),
                 cbind(city='sydney',datasets_sydney[[2]]))
```


```{r }
# combine all listing dataframes
all_listings <-  bind_rows(cbind(city='madrid', datasets_madrid[[1]]), 
                 cbind(city='barcelona',datasets_barcelona[[1]]),
                 cbind(city='melbourne',datasets_melbourne[[1]]),
                 cbind(city='sydney',datasets_sydney[[1]]))
```



```{r }
# change column names
colnames(all_calendar)[2] <- "id"
```


```{r }
# join datasets
library(dplyr)
all_data <- full_join(all_calendar, all_listings, "id")

```

```{r }
# filter on date (delete all after June)(calendar dataset)
library(dplyr)
all_calendar <- all_calendar %>% filter(between(date, as.Date('2022-03-25'), as.Date('2022-06-05')))

```

```{r }
# filter on date (delete all after June)(listings dataset)
library(dplyr)
all_data <- all_data %>% filter(between(date, as.Date('2022-03-25'), as.Date('2022-06-05')))

```

```{r }
# filter columns
drop <- c("listing_url", "scrape_id", "last_scraped", "description", "neighborhood_overview", "picture_url", "host_url", "host_name", "host_since", "host_location", "host_about", "host_response_time", "host_response_rate", "host_acceptance_rate", "host_thumbnail_url", "host_picture_url", "host_neighborhood", "host_listings_count", "host_total_listings_count", "host_verification", "host_has_profile_pic", "host_identity_verified", "latitude", "longitude", "bathrooms", "bathrooms_text", "minimum_minimum_nights", "maximum_minimum_nights", "minimum_maximum_nights", "maximum_maximum_nights", "minimum_nights_avg", "maximum_nights_avg", "calendar_updated", "availability_30", "availability_60", "availability_90", "availability_365", "calendar_last_scraped", "number_of_reviews_ltm", "number_of_reviews_l30d", "first_review", "last_review", "license", "instant_bookable", "calculated_host_listings_count", "calculated_host_listings_count_entire_homes", "calculated_host_listings_count_private_rooms", "calculated_host_listings_count_shared_rooms", "city.y", "price.y", "minimum_nights.y", "maximum_nights.y")

data_without_dropped_columns <- all_data[ , !(names(all_data) %in% drop)]
  
```

```{r }
# filter columns
drop_2 <- c("available", "adjusted_price", "host_is_superhost", "host_neighborhood", "host_verifications", "bedrooms", "beds", "amenities", "minimum_nights_avg_ntm", "maximum_nights_avg_ntm", "has_availability", "number_of_reviews", "review_scores_accuracy", "review_scores_cleanliness", "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value", "reviews_per_month")

data_we_will_use <- data_without_dropped_columns[ , !(names(data_without_dropped_columns) %in% drop_2)]
```

```{r }

```

```{r }
# change data type of price to integer
library(dplyr)
glimpse(data_we_will_use)
colnames(data_we_will_use)[4] <- "price"
data_we_will_use$price <- gsub("$", "", data_we_will_use$price)
data_we_will_use$price <- as.integer(data_we_will_use$price)

```

```{r }
#Saving new dataset
write.csv(data_we_will_use,'Filtered F1 Data.csv')
```

```{r}
Filtered_F1_Data <- read_csv("Filtered_F1_Data.csv")
```



```{r }
# make summary plot of all prices of all cities throughout the year 2022

```




```{r }
# What to filter


# alle data ver in de toekomst (done)
# niet nuttige variaelen  bijv. listings, host info, picture url, latitude/longtitude
```






