---
title: "Manuscript_analysis"
output:
  pdf_document: default
  html_document pdf: default
date: "2022-10-12"
authors: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r installation, include=FALSE}
# load packages
install.packages("modelsummary", repos ='http://cran.us.r-project.org')
install.packages("funx", repos ='http://cran.us.r-project.org')
install.packages("tidyverse", repos ='http://cran.us.r-project.org')
install.packages("cli", repos ='http://cran.us.r-project.org')

```

```{r load}
library(modelsummary)
library(tidyverse)
library(fixest)
library(cli)
```

```{r load_data}
#load data
filtered_australia <- read_csv("../..//gen/data-preparation/output/filtered_australia.csv")
filtered_spain <- read_csv("../..//gen/data-preparation/output/filtered_spain.csv")
final_airbnb <- read_csv("../..//gen/data-preparation/output/final_airbnb_dataset.csv")
```

```{r plot_spain}
# make new dataframe to calculate average for spain
grp_avg_spain <-
  filtered_spain %>%
  group_by(event_city, date) %>%
  summarise(price = mean(price)) %>%
  arrange(date, event_city)


#plot spain 
ggplot(grp_avg_spain, aes(x = date, y = price, color = factor(event_city), group = event_city )) + 
  geom_line() 
```

```{r plot_australia}
# make new dataframe to calculate average for australia
grp_avg_australia <-
  filtered_australia %>%
  group_by(event_city, date) %>%
  summarise(price = mean(price)) %>%
  arrange(date, event_city)


ggplot(grp_avg_australia, aes(x = date, y = price, color = factor(event_city), group = event_city )) + 
  geom_line() 

```

```{r modelsummary}
# Estimate (Australia)
model_1 <- feols(price ~ formula1 + event_city + 
                   formula1:event_city,
                 data = filtered_australia,
                 cluster = ~ id)

# Estimate (Spain) 
model_2 <- feols(price ~ formula1 + event_city + 
                   formula1:event_city,
                 data = filtered_spain,
                 cluster = ~ id)

# Estimate (Spain) with fixed effects 
model_3 <- feols(price ~ formula1 + event_city + 
                   formula1:event_city | accommodates,
                 data = filtered_australia,
                 cluster = ~ id)

# Estimate (Australia) with fixed effects 
model_4 <- feols(price ~ formula1 + event_city + 
                   formula1:event_city | accommodates,
                 data = filtered_spain,
                 cluster = ~ id)
```

```{r model_input}
# make output table in modelsummary 
cm <- c('(Intercept)' = 'Constant',
        'formula1'    = 'Formula 1 weekend',
        'event_city'    = 'Formula 1 city',
        'formula1:event_city' = 'Effect of formula1 difference')


models  <- list('Australia' = model_1, 
                'Spain' =  model_2,
                'Australia confounds' = model_3,
                'Spain confounds' = model_4)

```

```{r modeltable}
#table with models
modelsummary(models, coef_map = cm, stars = TRUE)
```

# Sources
